config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'
  get '/signup', to: 'static_pages#signup'
  post '/signup', to: 'companys#create'
  get '/login', to: 'static_pages#login'
  get '/auth/facebook/callback' => 'sessions#create_fb'
  post '/login', to: 'sessions#create'
  post '/sessions/create', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/employees/ofthemonth', to: 'employees#month'
  
  resources :companys do
    resources :employees, shallow: true
  end

  resources :projects, shallow: true do
    resources :tasks do
      resources :comments
    end
  end
  
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :project
    belongs_to :employee
    has_many :comments
    validates :content, presence: true

    def status
    end
end

app/controllers/task_controller.rb
class TaskController < ApplicationController

    def index
    end

    def new
    end
    
    def create
    end
    
    def show
    end

    def update
    end

    def destroy
    end
    
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :require_login
    before_action :set_task, only: [:show, :edit, :update, :destroy]
    before_action :set_user, only: [:show, :edit]

    def index
        @tasks = Project.find(params[:project_id]).tasks
    end
    
    def new
        @task =Task.new
        @project = Project.find(params[:project_id])
    end

    def create
        @task = Task.new(task_params)
        if @task.save
            redirect_to task_path(@task)
        else
            @project = Project.find(params[:project_id])
            render :new
        end
    end

    def show
        @comment = Comment.new
        @comments = @task.comments.all
    end

    def edit
    end

    def update
        if current_user.lead
            params[:task][:due_date] = flatten_date_array(params[:task])
            if @task.update(task_params)
                redirect_to task_path(@task)
            else
                render :edit
            end
        end
        
        if !current_user.lead
            if !@task.employee.nil?
                if params[:task]
                    @task.update(task_params)
                else
                    @task.employee_id = nil
                    @task.save
                end
            else
                @task.employee_id = current_user.id
                @task.save
            end

            redirect_to task_path(@task)
        end

    end

    def destroy
        if :project_lead?
            @task.comments.each do |comment|
                comment.destroy
            end
            @task.destroy
            redirect_to project_path(@task.project)
        else
            return head(:forbidden)
        end
    end

    private

    def task_params
        params.require(:task).permit(:content, :lead_notes, :completed, :employee_id, :project_id, :due_date)
    end

    def set_task
        @task = Task.find(params[:id])
        require_company_permission(@task.project.company_id)
    end

    def flatten_date_array(date_hash)
        %w(1 2 3).map {|e| date_hash["date(#{e}i)"].to_i }
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
  
<%= form_for @task, url: url, method: method do |f| %>
    <% if @task.project_id.nil? %>
        <%= f.hidden_field :project_id, value: params[:project_id] %>
    <% end %>
<!--
    Select A Project for this Task: <%= f.collection_select(:project_id, Project.active_projects(session[:company_id]), :id, :name) %> 
-->
    Title: <%= f.text_field :content %>
    Due Date: <%= f.date_select :due_date, default: Date.tomorrow %>
    Notes for Employees: <%= f.text_area :lead_notes %>

    <%= f.submit "Submit Task"%>
   
<% end %>

app/views/tasks/edit.html.erb
<h2>Edit This Task</h2>

<%= render partial: 'layouts/error_message', locals: {object: @task} %>

<%= render partial: 'form', locals: {url: {controller: 'tasks', action: 'update'}, method: 'patch'} %>

app/views/tasks/new.html.erb
<h2>Create A New Task for <%= @project.name %></h2>

<%= render partial: 'layouts/error_message', locals: {object: @task} %>

<%= render partial: 'form', locals: {url: {controller: 'tasks', action: 'create'}, method: 'post'} %>

app/views/tasks/show.html.erb
<h1>Task: <%= @task.content %></h1>

<h3>Task Status: <%= @task.status%></h3>

<% if @task.status == "Unassigned" && !@curr_user.lead%>
    <%= link_to 'Claim this Task', task_path(@task), method: 'patch' %>
<% end %>
<% if @task.status == "In Progress" %>
    <%if @task.employee == @curr_user %>
        <%= form_for @task do |f| %> 
            <%= f.hidden_field :completed, value: true %> 
            <%= f.submit "Mark this Task as Complete" %>
        <% end %>
        <%= link_to "Drop this Task", task_path(@task), method: 'patch' %>
    <% else %>
        <h4>Assigned to <%= link_to @task.employee.full_name, employee_path(@task.employee) %> </h4>
    <% end %>
<% end %>


<h3>Task due on: <%= due_date_formatted(@task) %></h3>

<h3>Project Lead: <%= project_lead_name(@task.project) %></h3>

<h3>Notes from Project Lead:</h3>
<p><%= @task.lead_notes %></p>

<% if @curr_user.lead %>
    <br><%= link_to 'Edit Task', edit_task_path(@task) %>
    <br><%= link_to 'Delete Task', task_path(@task), method: :delete, data: {confirm: "Are you sure you want to delete this task? This will also delete its comments."} %><br>
<% end %>

<h4>Add a Comment Below:</h4>
<%= render 'comments/form' %><br>

<h4>Comments:</h4>
<ol>
<% @comments.each do |comment| %>
    <li>
    <%= comment.content %><br>
    Posted By: <%= comment.employee.full_name if comment.employee %>
    </li>
<% end %>
</ol>

<h4><%= link_to "Back to Current Project", project_path(@task.project) %></h4>